### ISSUE TITLE
NPC's missing from Ships

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#269] opened 2023-09-26 04:38 UTC
At some point in the game, ships will no longer spawn NPC's. Ships will land but no one comes out and when you go inside to ship, you'll find no one is inside either. This bug seems to prevent completion of quests such as "Ground Pounder" as Spacer ships are supposed to land and drop off soldiers, but no one comes out. This is not exclusive to enemy NPC's, as friendly NPC's don't spawn either.

---

## Game Version
1.7.33

## New Game
Yes

## Reproduction Steps
I have not been able to recreate it but I found that others have had this issue as well. I have reloaded an old save around level 40 which still had enemies coming out from the ship but after a few level ups and missions, the NPC's don't seem to spawn again.

**Comment by Constellation-VASCO** [comment] 2023-10-27 17:06
There is a mod out that should fix this issue:

https://www.nexusmods.com/starfield/mods/5668

**Comment by Aurelianis** [comment] 2024-05-19 16:24
Closed as duplicate of https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/221

**Closed by Aurelianis** 2024-05-19 16:24 UTC
Labels: Platform: PC (Steam), Type: NPCs
