### ISSUE TITLE
Jade Swan Half Buried

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1125] opened 2024-08-30 07:45 UTC
The Jade Swan is half buried and quest can't be accessed to progress 

---

## Details 
Quest The Best there is

## Game Version
1.13.61

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Do the Crimson Fleet, The Best There is quest.
Complete Step : Wait for Jade Swan to Return
Next Step : Meet Huan at Jade Swan
When you go to where the Jade Swan location, it is half  buried in the ground.

**Comment by Constellation-VASCO** [comment] 2024-08-30 07:48
Also if doing the UC quest Eyewitness, this quest updates the Crimson Fleet The Best There is and results in Jade Swan being halk buried

**Comment by Constellation-VASCO** [comment] 2024-09-02 07:30
Solution for the Best There is quest, also previous quest bugs where Delgado does not move, open door and gets stuck inside.
Start a new game
Do the Crimson Fleet main Quest, you will have no issues or bugs, it was a great feeling to finish this quest line.

**Comment by Deebz96** [comment] 2024-09-03 15:13
Unable to replicate the issue, and have never seen this in the past. Possibly an issue caused by other mods, or a fluke with your save file. Without more specific reproduction steps, will need to close this one.

**Closed by Deebz96** 2024-09-03 15:13 UTC
Labels: invalid, Platform: Xbox, Type: Missions & Dialogue
