### ISSUE TITLE
Standing up from cockpit inside wall

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#60] opened 2023-09-05 20:33 UTC
Every time I stand up from my ship's pilot seat, I'm using the standard Frontier, the character seems to be half stuck inside the left side of the cockpit, and it takes some jumps/sprints to get unstuck

---

## Details 
Nothing, happens no matter where or when, it's probably just a mesh colliding issue

## Game Version
1.7.23

## New Game
Yes

## Reproduction Steps
Just sit and stand up, for me it happens every single time

**Comment by Aurelianis** [comment] 2024-05-19 15:13
Unable to reproduce. No matter how many times I exit the pilot seat in the Frontier I'm always behind it and not stuck. It's possible this was fixed by Bethesda since this was reported. Closing as unable to reproduce.

**Closed by Aurelianis** 2024-05-19 15:13 UTC
Labels: Platform: PC (Steam), Type: Ships
