### ISSUE TITLE
Stuck in Conversation with Walter Stroud

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#79] opened 2023-09-07 16:55 UTC
During All That Money Can Buy, talking to Walter Stroud at the end of the quest will lock you into the dialogue zoom in after he finishes talking. It happens regardless of whether you speak to him directly or if he talks to you through the ship while you are in the pilots seat. The only way to get out of it is to use the kill command on Walter. It essentially locks your game as fast travel is disabled due to the following events in game and Walter will initiate the dialogue even if you sit in the pilot's seat. Dialogue choices don't matter either.

---

## Details 
Walter Stroud: 00005998
All That Money Can Buy: 002C1C9B
Others having the same issue.
https://www.reddit.com/r/Starfield/comments/16aea8v/i_am_stuck_in_dialogue_on_the_mission_all_that/

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
During the mission All That Money Can Buy, on the objective to get back on the ship, speak to Walter onboard your ship or sit in the pilot's seat as the waypoint shows. After he says the line about him making a pun, you will be given quest rewards yet the screen will stay zoomed as if you're still in a conversation. Nothing further will happen.

**Comment by scifisi** [comment] 2023-10-19 19:46
I can concur, this is happening to me also. This needs fixing

**Comment by Constellation-VASCO** [comment] 2023-11-14 09:08
Also happened to me. I am waiting for a fix, but the quest is still bugged after the patches.

**Comment by TESWartortle** [comment] 2023-12-17 19:14
Can't replicate with 1.8.88

**Comment by Aurelianis** [comment] 2024-05-19 04:01
This seems to have been fixed by Bethesda. Closing as unable to reproduce. If it does occur again please let us know.

**Closed by Aurelianis** 2024-05-19 04:01 UTC
Labels: Platform: PC (Steam), Type: Missions & Dialogue
