### ISSUE TITLE
No NPCs in ships that land on planet surfaces

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#470] opened 2023-10-29 14:28 UTC
All ships that land while you're on a planet are empty, no NPCs exit the ships and no NPCs are inside the ships.

---

## Details 
Enemy ships (like ecliptic and Starborn ships) and settler ships don't even open their landing bay doors. Friendly ships where the NPCs don't normally exit the ship like UC Vanguard ships do have open bay doors but there are no NPCs inside the ship.
I've made sure it's this mod that's causing the issue, and have tried two different saves, one old and one new. All are the same, ships land like normal but there are never any NPCs inside or coming out of the ships.

Ships I've checked more than three times:
Ecliptic ships
Spacer ships
Starborn ships
UC Vanguard ships
Freestar collective ships
Settler ships

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Install this mod is all, without it everything is normal, with it all landed ships are empty of NPCs.

**Comment by Constellation-VASCO** [comment] 2023-10-29 14:37
I do not have the community patch and the same issue is occurring; it also occurs during boarding actions - ships are routinely ghost ships. The Starborn ships each have the same cargo (4 vytnium rods) and nothing in the Captain's Locker.

**Comment by Constellation-VASCO** [comment] 2023-10-30 02:59
I have this issue. Starborn ships land and nothing comes of it. Visiting landed ships is pointless.

This is both Vanilla and post current patches.

**Comment by kayahr** [comment] 2023-11-16 07:50
May be a duplicate of issue #268

**Comment by Aurelianis** [comment] 2024-05-19 21:23
This is related to https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/221 and has been fixed by Bethesda.

**Closed by Aurelianis** 2024-05-19 21:23 UTC
Labels: Platform: PC (Xbox), Type: NPCs
