### ISSUE TITLE
Soft lock in Groundpounder

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#69] opened 2023-09-06 16:09 UTC
There is a soft lock that occurs when trying to open the door to speak to the doctor. The door is supposed to be accessible when all enemies are cleared but will not advance even if this has already happened.

---

## Game Version
1.7.23.0

## New Game
Yes

## Reproduction Steps
Start the quest as normal, and reach the point where you have to speak to the doctor.

**Comment by TESWartortle** [comment] 2023-12-17 04:24
Same issue as #74 . Unable to reproduce on 1.8.88 multiple ways. 
QUST 001F3A36 MS01
Stage 420 unlocks the door, set when all spacers killed from RefAlias 61 InfirmarySpacers - has defaultcollectionaliasondeath with StageToSet = 420: seems correct

Possible an enemy gets spawned off the map? Probably a real bug with two reports, but unable to replicate at this time and seems set up correctly to me. Should look again in the CK

**Comment by Aurelianis** [comment] 2024-05-19 02:53
This was fixed in v1.9.47.0
"Groundpounder: Fixed an issue where the door to Lezama could sometimes be locked"

**Closed by Aurelianis** 2024-05-19 02:53 UTC
Labels: Platform: PC (Steam), Type: NPCs
