### ISSUE TITLE
Dr Banglawala only detects minerals in inventory

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#271] opened 2023-09-26 23:28 UTC
After travelling to another planet, the player can randomly encounter Dr. Sohla Banglawala, who will hail the player's ship and ask them for three random different types of minerals. Dr Banglawala will only take items from the player if they are in the players' inventory, rather than their ship's cargo hold, which is inconsistent with other similar types of encounters such as the LIST Settlers ship encounter who will ask for 20 Iron and will accept it from the cargo hold.

---

## Details 
NPC_ (00063A81) 'Dr. Sohla Banglawala'

## Game Version
1.7.33.0

## New Game
Yes

## Reproduction Steps
1. From any ship, fly to a new planet or star system, eventually you will encounter Dr. Sohla Bangawala in a ship
2. Accept her hail, or hail her ship and select the first option "I have more than enough rocks to offload, I'll help if I can."
3. Note the three samples that Dr. Sohla asks for, then press Tab to exit the conversation
4. Add five of each samples she asks for to your inventory and talk to Dr. Sohla again with the same option as before, you will this time be given the option to give her any of the three samples
5. Exit the conversation again and place the minerals in your inventory in your cargo hold
6. Talk to Dr. Sohla again and you will no longer have the option to give her any of the samples

**Comment by Constellation-VASCO** [comment] 2023-11-26 01:59
Still a problem in latest release of game 1.8.86 (PC). Cargo hold of ship is not checked for requested resources.

**Comment by Constellation-VASCO** [comment] 2023-12-11 06:58
I can confirm that this is the case. I came here to report the same issue.

**Comment by Aurelianis** [comment] 2024-05-19 15:31
Closing as duplicate of https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/56

**Closed by Aurelianis** 2024-05-19 15:31 UTC
Labels: Platform: PC (Steam), Type: Missions & Dialogue
