### ISSUE TITLE
Sam's response to Cora's joke ... Barrett's dead

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#679] opened 2023-11-25 22:51 UTC
After Cora tells the joke about jumping skyscrapers, Sam's response after laughing as every good father should, was for her to tell Barrett next time she see's him. Even if Barrett is dead.

This dialog should not happen if Barrett is dead, or Sam's response should be cut off after he laughs and says 'good one.'

---

## Details 
Random dialog even in the ship with Sam as a crew member.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Fly along with Sam, and therefor Cora, in your crew after Barrett dies in the Hunter's attack. This joke will come up as a random background dialog.

**Comment by Pickysaurus** [comment] 2023-12-08 18:59
Duplicate of #638

**Closed by Pickysaurus** 2023-12-08 18:59 UTC
Labels: Platform: PC (Steam), Type: Audio
