### ISSUE TITLE
in to the unknown temple 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#846] opened 2024-01-28 13:42 UTC
I go to the eta temple , complete the ring puzzle , get booted to the outside , the power symbol shows and it tells me to go to the lodge , also tells me to open up the menu to equip the anti grav power , open up the power menu but there is no power to select . 

---

## Details 
have tried going back to earlier save before mission has started , tried console commands, verifying files , and a full reinstall of the game . nothing works 

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
go to the eta temple , complete the ring puzzle , get booted to the outside , the power symbol shows and it tells me to go to the lodge , also tells me to open up the menu to equip the anti grav power , open up the power menu but there is no power to select .

**Comment by Pickysaurus** [comment] 2024-01-30 11:05
This seems to be a one-off glitch in your save. Try adding the power via the console or rolling back to a save before it went wrong.

**Comment by Aurelianis** [comment] 2024-05-19 19:38
Many of the issues with Into The Unknown and the temple have been fixed by Beth since v1.8.86.0. This was most likely a corrupt save issue or possibly was fixed by Beth. Closing as unable to reproduce.

**Closed by Aurelianis** 2024-05-19 19:38 UTC
Labels: Platform: PC (Steam), Type: Perks & Skills
