### ISSUE TITLE
Madame Sauvage stalks player around her bar

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#27] opened 2023-09-02 21:49 UTC
Madame Sauvage from Madame Sauvage's Place in Neon City Ebbside district stalks the player all over her bar for some reason.  I think she has the typical shopkeeper "keep them out of trouble by following them" AI package, but she shouldn't.  She'll literally follow you up to the third floor while you're joining a gang and then stand at the door to offer you a drink.

---

## Details 
Neon_DominiqueSauvageRef 22f282
CityNeonMadameSauvage

## Game Version
1.7.23.0

## New Game
Yes

## Reproduction Steps
From the main menu (don't even have to start a game) open the console and run "coc CityNeonMadameSauvage".  Go talk to Madame Sauvage at the bar, then talk to Andrea to the right.  Ask Andrea about the Disciples, then say you want to join the gang and follow her upstairs.  Either wait a few minutes or go through the dialogue with the boss of the street gang, and then walk to the door on the third floor, and you'll see the bartender/owner standing there stalking you.  She doesn't talk to anyone up there or have special dialogue that I can see, she just... follows you around.

**Comment by Aurelianis** [comment] 2024-02-29 02:13
I believe this is the intended behavior. She has a package Neon_VendorSandboxandKeepEyeOnPackage [PACK:00192C62]. Both her and Dietrich Sieghart use this package. The package is set up for them to keep an eye on you while you are in their establishment. There's another package that does the same thing for the Trade Authority in Neon and other vendors in other locations like New Atlantis also have packages that are set up for them to keep an eye on you.

**Comment by Constellation-VASCO** [comment] 2024-03-13 12:44
Package should limit to a certain sandbox, shouldn't it? That's the way I've always seen them. If so we'll need CK to see exactly where and what it extends to. I've personally never seen her go upstairs. A bunch of them will follow, like the medic in the Well will also come running if you go in the back of her establishment, but it's limited to that area.

**Comment by Constellation-VASCO** [comment] 2024-03-31 08:21
I think it is intended. Reminds me of the psychotic NPCs from Oblivion, when you entered their houses or shops.
Granted, she's very "territorial".

**Comment by Constellation-VASCO** [comment] 2024-04-06 19:35
Not a particularly bug per se, more a feature. Even if it's a necro thread, it's worth mentioning that it was *fixed* in SF Civis Vendors More Credits Gradually Increased mod ver. 1.5.

**Comment by Aurelianis** [comment] 2024-05-19 04:36
Closing as out of scope. This is not really a bug and out of scope for SFCP.

**Closed by Aurelianis** 2024-05-19 04:36 UTC
Labels: Platform: PC (Steam), Type: NPCs
