### ISSUE TITLE
New Atlantis Elevator Well - Spaceport - Waterfall

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1040] opened 2024-06-22 17:58 UTC
After terramorph attack on New Atlantis spaceport, the elevator to the well no longer functions

---

## Game Version
1.12.32.0

## New Game
Yes

## Reproduction Steps
Complete Vanguard quest, though it happens after terramorphs attack new Atlantis, sometime after the spaceport area is back to normal, the elevator stops working

**Comment by Deebz96** [comment] 2024-09-02 02:04
Dupe of #839

**Closed by Deebz96** 2024-09-02 02:04 UTC
Labels: duplicate, Platform: Xbox, Type: Locations
