### ISSUE TITLE
Elevator bug 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#613] opened 2023-11-12 21:36 UTC
Jemison spaceport, elevator to Waterfall (etc) stops working after UC Vanguard questline.

---

## Details 
After the spaceport is destroyed and rebuilt, whilst the elevator is still there, it seems the game forgets to put the functions of it back into place resulting in a useless elevator (which can affect several quests). 

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
As per previous note.

**Comment by Pickysaurus** [comment] 2023-11-14 19:42
Duplicate of https://www.starfieldpatch.dev/issues/343

**Closed by Pickysaurus** 2023-11-14 19:42 UTC
Labels: Platform: PC (Xbox), Type: Locations
