### ISSUE TITLE
starfield trackers alliance quest

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1155] opened 2024-09-14 16:56 UTC
Scanner quest completion conditions are not displayed.
Scanner Quest is not progressing
Tracker Alliance mission board quest is not progressing

---

## Details 
Please note that the Japanese is translated into English at DeepL.

The point of occurrence is unknown, but at some point a glitch occurred in the scanner quests and mission board quests of the Tracker Alliance.
The clear condition (kill or live) that is displayed when scanning is no longer displayed in either case.
These NPCs do not respond at all when spoken to or when a pickpocket command is executed.
In addition, the quest does not progress even if the NPC in question is stunned by EM weapons, and killing them will force the quest to be treated as a failure.
The same problem with Hannibal, who is encountered during the Starjacker quest, can be solved by talking to him, but it is still possible to proceed with the quest. However, the dialogue was not displayed correctly and a mini-game of persuasion suddenly started.

Translated with DeepL.com (free version)

## Game Version
V1.13.61.0

## Language
日本語 (JA)

## New Game
No

## Reproduction Steps
not

**Comment by Deebz96** [comment] 2024-09-14 17:06
Duplicate of #1034

**Closed by Deebz96** 2024-09-14 17:06 UTC
Labels: duplicate, Platform: PC (Steam), Type: NPCs
