### ISSUE TITLE
Z-Fighting on top of big bang's ammo counter disp.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1011] opened 2024-06-15 00:27 UTC
There is Z-fighting on the top of the big bang's ammo counter display when it appears. The display also disappears after reloading the weapon. Before I first downloaded the community patch, I didn't even know the big bang had an ammo count display. 

---

## Game Version
1.12.32.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Equip the big bang and observe the little gauges on the very top of the big bang weapon as they flicker, and then reload the weapon and observe that the entire ammo counter display is gone.

**Comment by Deebz96** [comment] 2024-09-28 20:37
Dupe of #707

**Closed by Deebz96** 2024-09-28 20:37 UTC
Labels: duplicate, Platform: Xbox, Type: Items
