### ISSUE TITLE
Missed Beyond Measure Companion

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#545] opened 2023-11-05 16:53 UTC
After completing the funeral in 'Missed Beyond Measure' I got the notification that Sarah Morgan has become my companion. She also appears in the crew list unassigned. Talking to vasco and asking him to be my companion releases Sarah from being my companion and allows me to get my original companion back.

---

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
1.) Complete the funeral
2.) Walk outside the lodge

Others have reported the same thing in the steam forums here: https://steamcommunity.com/app/1716740/discussions/0/3882722163301436596/

**Comment by Aurelianis** [comment] 2024-04-25 01:50
I just came here to see if this had been reported. I never once had this bug until today and I've played A LOT. The only difference is that today I was going through all options for testing some things and had married Sarah (which I had never done before in any other playthrough). So it seems this bug only happens if you are committed to Sarah and she is the companion that dies in High Price to Pay. And it is still there in 1.10.32 which is the version I'm on now.

**Comment by Constellation-VASCO** [comment] 2024-04-25 07:01
Before going to funeral:
1. if Sarah dead -> use console command player.hasperk 1c514c
2. if returns 1 -> use player.removeperk 1c514c
3. go to funeral and see if it happens again
CompanionCheck perk are *not* removed if you still have one companion following you before traveling to Unity (issue #940). The perk remains "hooked into" even if the respective companion is no longer following you at the start of NG+.
Although I didn't check the issue (funeral, with dead wife), I have the tiny impression that CompanionCheck perks are the culprits (may also happens with Andreja 1c5150, Barrett 1c514e or Sam 1c514d)

**Comment by Aurelianis** [comment] 2024-04-25 13:42
It doesn't have anything to do with her perk. I need to look at what happens during the commitment ceremony for Sarah because something is happening there that causes the bug.

**Comment by Constellation-VASCO** [comment] 2024-04-25 19:03
"It doesn't have anything to do with her perk."
The perk should also be removed once your digital wife/husband is dead. Did you check this? I cannot reproduce since my digital wife is long gone (NG+ 5) along with previous saves.
---------------
"are you sure you don't have a mod doing something with them?"
Snarky question. I probably *know* what mods I'm using and what they do.
----------------
"They are removed when you dismiss a companion"
True. I also said "CompanionCheck perks are not removed if you still have one companion following you before traveling to Unity" and "The perk remains "hooked into" even if the respective companion is no longer following you at the start of NG+." 
----------------
Funny thing when Andreja is threatening me with her goons while 1c5150 = 1. (NG+ start). My Great Serpent calmed her and she gave me the artifacts without a fight.

**Comment by Aurelianis** [comment] 2024-04-25 21:00
It was not a snarky question at all. I don't even know who you are. It just shows as Constellation-VASCO here on github. 

Anyway, this bug ONLY happens if Sarah is committed to you when she dies. It does not happen otherwise.

**Comment by Aurelianis** [comment] 2024-04-25 21:48
Found the issue. 

Fragments:Quests:QF_MQ206A_002BACF9

Function Fragment_Stage_2000_Item_00()
<bunch of code here>
  **ElseIf COM_Quest_SarahMorgan_Commitment.IsRunning()** || COM_Quest_SarahMorgan_Q01.IsRunning()
    (SQ_Companions as sq_companionsscript).SetRoleActive(SarahMorganREF, True, True, 0.0, 0.0)
    SarahMorganREF.EvaluatePackage(False)
  EndIf
  Alias_LodgeBed.GetRef().BlockActivation(False, False)
EndFunction

The issue is that Sarah's Commitment quest doesn't shut down like it should so she is set as active again.

I just went back to a previous save after finishing Sarah's Commitment quest and even though it shows as completed in my log, getquestrunning shows that it is still running. I forcibly shut it down via console and the bug didn't occur.

**Comment by Aurelianis** [comment] 2024-04-25 22:20
Ok, there's a lot going on with that Commitment quest and how it shuts down, so as a workaround, I added a check to the script for Missed Beyond Measure that adds a check for Sarah:
  ; SFCP Adds a check for DeadCompanionREF == SarahMorganREF to shut down her Commitment quest before checking to see if it is running later in this script. This is a workaround for Issue #545
  If DeadCompanionREF == SarahMorganREF && COM_Quest_SarahMorgan_Commitment.IsRunning()
    COM_Quest_SarahMorgan_Commitment.Stop()
  EndIf

I tested it and it works just fine.

This is without the script after Missed Beyond Measure after Sarah dies in High Price to Pay:
![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/109992824/f154f791-0909-4416-80ec-92334abdb42a)

And with the script after Missed Beyond Measure after Sarah dies in High Price to Pay:
![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/109992824/71179b99-49a0-4fe0-a09e-5c65dfae9c13)

[SarahDeadLockedInFix.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/15122650/SarahDeadLockedInFix.zip)

**Comment by Aurelianis** [comment] 2024-04-25 22:35
Removed the Fix Ready tag. I'm going to do a pull request and add this to the update handler script instead of modifying a vanilla script. This way we can also retroactively fix the issue if someone already finished Commitment: Sarah Morgan, High Price to Pay with Sarah dying and finally Missed Beyond Measure. I can add a check to remove Sarah from the active role.

**Comment by Aurelianis** [comment] 2024-04-27 21:18
Found that none of the companion commitment quests were stopped at any point if they were the companion who dies in High Price to Pay. Most players probably never stop in the middle of a commitment quest to finish High Price to Pay, but this could have lead to the same issue seen with Sarah so I added an OnStageSet to the SFCP update handler to shut down any running commitment quest for the companion who dies in High Price to Pay.

**Closed** 2024-05-18 17:18 UTC
Labels: Platform: PC (Steam), Type: Missions & Dialogue, Fix Ready
