### ISSUE TITLE
August vehicle update

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1106] opened 2024-08-21 11:39 UTC
New rover vehicle added to game in August update will not appear in inventory or show up next to ship after purchase

---

## Details 
I am able to go to a ship technician and purchase a vehicle, credits are removed from my player, but no vehicle appears.  Reloading the game doesn't help, uninstalling and reinstalling this patch also doesn't help, clearing the cache for Starfield also doesn't help.  I tried disabling this patch and when doing so the vehicle appears as expected in game and is able to be used.

## Game Version
1.13.61

## Language
English (EN)

## New Game
No

## Reproduction Steps
load game after vehicle update, go to ship technician, buy vehicle, activate it, exit ship technician.  Vehicle should show up parked next to ship.  It will if Community patch is disabled, it won't if Community patch is enabled.

**Comment by Deebz96** [comment] 2024-08-21 12:25
Been investigating this one. It’s not directly caused by this mod, and probably not any of the other mods people have reported as being the cause of this issue, but there is something weird going on. It works fine for most people, but not some people. I’m not able to reproduce this issue myself.

Vehicles work through the ship hanger system, and purchasing a new vehicle works the same as purchasing a ship module. The SFCP touches nothing about how this system works.

Users are reporting that loading a save with the buggy spawned in, then going to a save from before purchasing it, will correct the issue. Presumably, spawning then deleting a vehicle via the command console will also allow them to be purchased.

I have reported the issue to Bethesda. I don’t believe there is any action to be taken on the SFCP’s side at this time, unless more information about the issue can be provided.

**Comment by Constellation-VASCO** [comment] 2024-08-21 12:33
Thanks Deebz96.  I'll give your suggestions a shot.

**Comment by Deebz96** [comment] 2024-08-22 05:21
I have a possible lead on what this issue may be, but I have not yet been able to link it to the SFCP. I have identified a mod which can cause this exact issue on my end, and in that case, it's caused by an outdated Player NPC_ record which lacks a new component named BGSVehicleManagement.

The SFCP used to modify this record, but no longer does. The issue I'm seeing with this other mod is identical to what is being described though, so it's more than a coincidence in my mind. If anyone with a bit of modding experience is experiencing this problem, and wants to dig around on their end to see if something weird may be going on with the Player record, I'll take any help I can get right now.

**Comment by Deebz96** [comment] 2024-08-23 18:02
As far as I can tell, this is caused by one of two things:

1: Using an outdated version of the SFCP. This is especially possible with the creation club platform, as it will outright lie about your mods being up to date. Need to completely uninstall and reinstall them to properly update.

2: Another mod which touches the player record, and also lists the SFCP as a master, may be at fault. Disabling the SFCP would also prevent that mod from loading, making it appear that the SFCP is at fault. I don’t know what mod this would be, but it’s a possibility at least.

This issue seems squarely related to an outdated player record though (form id 00000007), so I don’t believe there is anything to fix on the SFCP side at this time. Will leave the ticket open in case more info comes along though.

**Comment by Deebz96** [comment] 2024-08-25 18:53
Going to close this issue now, as I am very certain this is mostly down to people using outdated builds of this mod.

**Closed by Deebz96** 2024-08-25 18:53 UTC
Labels: invalid, Platform: PC (Steam), Type: Placed Objects
