### ISSUE TITLE
'Starborn' Questline

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#121] opened 2023-09-10 05:58 UTC
After the 'All that money can buy' Mission, you immediately blast off into orbit above neon and speak with an unknown ship called 'Helix'. You then have to either run away, fight, or jettison the artifact you just got. No matter which option I choose I am prevented from landing anywhere in the universe once I grav-boost back to the planet Jamison. I am stuck in space unable to dock anywhere, land anywhere, and fast travel anywhere. Whenever I click on a location on the map I get the message "Fast Travel is currently unavailable from this location"

Others with the same issue on reddit:
https://www.reddit.com/r/Starfield/comments/16dikxy/starborn_quest_fast_travel_bug/

---

## Details 
'Starborn' Quest, not sure of the quest ID

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
I am about 30 hours into my current save so I can't recreate it easily. I was able to go back multiple saves and keep running into the issue.

**Comment by Constellation-VASCO** [comment] 2023-09-10 09:51
I made the mistake of using console commands to try to teleport ahead trying to fix this bug, all my saves are now stuck on this mission or a little further with the bug where I cannot fast travel anymore. I'm extremely frustrated, been trying to fix this for a few days now.. If anyone can find a fix to allow fast travel again, please let me know, I appreciate it!

**Comment by Constellation-VASCO** [comment] 2023-09-10 12:56
bwdodd, I found a console command that worked. Once you are in space and can't land anywhere, use 'ResetInputEnableLayer 3' and if that doesn't work use 'ResetInputEnableLayer 4'. 3 didn't work for me, but 4 did.

**Comment by Aurelianis** [comment] 2024-05-19 04:02
This seems to have been fixed by Bethesda. Closing as unable to reproduce. If it does occur again please let us know.

**Closed by Aurelianis** 2024-05-19 04:02 UTC
Labels: Platform: PC (Steam), Type: Missions & Dialogue
