### ISSUE TITLE
Sustenance broken in latest update

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1043] opened 2024-06-23 06:46 UTC
Sustenance no longer working in main game after last patch. Reproduced on new game with only SKK fast start. Worked without community patch. Adding patch removed sustenance changes immediately.

---

## Details 
Sustenance no longer working in main game after last patch. Reproduced on new game with only SKK fast start. Worked without community patch. Adding patch removed sustenance changes immediately.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Add only SKK fast start to save time. Start new game. Change sustenance settings. Buy and consume food. Kept some food in inventory.

Added in Community patch. look in inventory, food no longer showing 'fed for 30 minutes'.

**Comment by Baarn** [comment] 2024-06-23 09:37
I could reproduce this:

Reproduction Steps:
Starting from Main Menu
`coc NATheLodge`
`player.additem 29B062 10` (Alien Sandwich)
In Gameplay Settings set Sustenance to` Positive & Negative`
(I set the setting to `Only Positive` and back to `Positive & Negative` to avoid the bug that doesn't properly save Gameplay Settings)
Opened Inventory, used one of the sandwiches.
No buff was applied.

I expected to be instantly debuffed when switching the gameplay settings. But at no time was a buff or debuff applied.

However I have a suspicion that this is caused by skipping over a specific point in the story and not by the community patch, going to do some further testing.

**Comment by Baarn** [comment] 2024-06-23 10:15
2nd Test:

Starting from Main Menu
Started a New Game
After the Elevator reached bottom, Gameplay Options set Sustenance to `Positive & Negative`.
(as expected at this point, there are no buffs and debuffs applied, this is vanilla behavior)
Continued playing through the tutorial.
Created a Character, created a save, reapplied Gameplay Options just to be sure.
(still no buff/debuffs applied as in vanilla)
Continued playing through the tutorial.
After dealing with the Crimson Fleet pirates I went to Barett to talk with him.
After the "forced dialogue" (can't tab out) with Barrett and Lin ends and it switches to the portion in which you can ask Barrett further questions, the game automatically hydrates and feeds you. (Same time at which Artifact Eta is added to the player)
Buffs are applied correctly during this stage.

Conclusion: Some sort of script seems to run that never gets applied when you skip over this specific portion of the tutorial.

I also loaded a save before talking to Barrett, set Sustenance to `Off`, completed the Dialogue (received Artifact, no buffs/debuffs applied as expected), then switched Sustenance to `Positive & Negative` and received both malnourished and dehydrated debuffs.

**Comment by Baarn** [comment] 2024-06-23 10:43
3rd Test (Community Patch disabled):

Repeated steps from first test (`coc NATheLodge`). 
No buff or debuff was applied.

**Comment by Deebz96** [comment] 2024-06-23 14:47
This was caused by the SFCP making a change to POE_SustenanceAllowed condition form, to fix the issue where Sustenance would not work in certain NG+ universes. I initially did this by replacing a condition check on the MQ101Debug global value, with a check to see if MQ101 has reached stage 9000 instead. The MQ101Debug global value is always 0 in the vanilla game, so that check seemed useless.

However, turns out that SKK Fast Start changes this value to 8, which is how Sustenance is enabled when using that mod. It does not complete stages 310 or 9000 in MQ101, like the vanilla NG+ universes do, so it does not work with modified SFCP condition form.

I have re-added that condition and rechecked each case where Sustenance should be enabled, to make sure it's all still working as expected. It now works correctly with SKK Fast Start as well. Fix attached below. This will be in the next version of the patch.

[SFCP_1043.zip](https://github.com/user-attachments/files/15945057/SFCP_1043.zip)

**Comment by Constellation-VASCO** [comment] 2024-06-24 12:38
Fantastic! Thanks so much for this quick fix.

**Comment by DJLegends1011** [comment] 2024-06-24 19:25
wondered why sustence was not showing up with SKK

**Comment by Deebz96** [comment] 2024-08-20 19:56
The issue this fix addresses has been fixed in the August update. Will remove the modified cndf from the next update of the mod.

**Closed** 2024-08-24 19:34 UTC
Labels: Platform: PC (Steam), Type: Items, Fix Ready
