### ISSUE TITLE
game keep track of companion affinity even without

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#708] opened 2023-12-01 10:43 UTC
.

---

## Details 
so, have you experienced the scenario where you are doing a quest or whatever else somewhere, alone or with a companion, then a activity pops up saying to "speak with companion" that is not your active one?

either I don't understand the mechanics or the game is seriously bugged, keeping track of companion affinity when you are not with them

I had "talk with sam coe" while traveling alone and again when travelling with andreja

doesn't make sense

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
.

**Comment by Constellation-VASCO** [comment] 2023-12-02 17:24
While it might not make sense why you psychically know that your companions want to chat, this is not a bug. There are several companion conversations that are independent of affinity or being your active follower. These are typically triggered by the passage of time or completing certain quests.

**Comment by Aurelianis** [comment] 2024-02-26 17:33
Having spent a ton of time on companions and how they work, this is not a bug. 

The Talk to objectives are triggered by time. If it is about an event, it is based on the time passed since said event completed. If it is for a story gate, it is real time passed when they are traveling with you.

I've marked this as invalid since it is not a bug.

**Closed** 2024-05-19 05:07 UTC
Labels: invalid, Platform: PC (Steam), Type: NPCs
