### ISSUE TITLE
[New Issue] All NPCs can only say "Oh no, what are we going to do now?"

### ISSUE THREAD

**Issue by Jac0Tac0** [Starfield-Community-Patch/Starfield-Community-Patch#918] opened 2024-03-25 05:54 UTC
After update 3 on Xbox all NPCs can only say "Oh no, what are we going to do now?". All dialogue interactions have been replaced by this one response. Usually it is not audible but only in a subtitle, but it has on occasion been spoken, even by traders in space. A few times I was able to play a quest without the bug appearing up to a point but if there is a step requiring me to speak with a character then they only say this line instead of mission dialogue and this halts the gameplay. I have tried to load earlier saves but the bug appears there also. Uninstalling and reinstalling also didn't work.  
![20240324_225058](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/72059561/3600a692-3c3e-4b82-9655-beed3410b56d)
![20240324_225114](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/72059561/b664aabb-d5bf-4ef4-8d5f-e171e74c84a4)
![20240324_225126](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/72059561/707eb0de-656c-41b5-9c42-0ade8c53e124)
![20240324_225219](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/72059561/a5490f5d-6ce8-42d1-a7bc-d31de65b2322)

### Details

First happened after receiving the ancient branch in Late Bloomer mission on Akila when returning to Jameson. In main quest on Freya 3 Nishina Research Station I was able to play quest up to the second objective requiring me to speak with Raphael after the pantry door key was used. Then he started saying the line too and it caused me to get stuck in the destroyed station universe without a vortex exit as these had not yet spawned. 

### Game Version

85391C36 V1.10.31.0

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

After update 3, speak with any NPC until they start saying "Oh no, what are we going to do now?" Then try to speak to other NPCs and pretty soon all will say this one lune and nothing else.

**Comment by gir489returns** [comment] 2024-03-26 01:26
Related to #915? Maybe this was introduced with the 1.10.31 patch.

**Comment by Deebz96** [comment] 2024-03-26 22:38
Fixed by Bethesda in 1.10.32.

**Comment by gir489returns** [comment] 2024-03-26 22:39
#915 was not fixed in 1.10.32, at least when I loaded my save that was next to them. I'll keep playing, hopefully it reloads or something.

**Comment by Deebz96** [comment] 2024-03-26 23:42
Should be. One of the two fixes was specifically targeted at this bug, and other players are reporting that it's fixed.

**Comment by gir489returns** [comment] 2024-03-26 23:43
> Should be. One of the two fixes was specifically targeted at this bug, and other players are reporting that it's fixed.

Where did you see that? There's no patchnotes posted with this change.

**Comment by Deebz96** [comment] 2024-03-26 23:50
"Addressed an issue that could cause characters to become stuck saying the same line of dialogue."

**Comment by gir489returns** [comment] 2024-03-26 23:51
> "Addressed an issue that could cause characters to become stuck saying the same line of dialogue."

Source: dude trust me bro? Where did you get this?

**Comment by Deebz96** [comment] 2024-03-26 23:55
https://twitter.com/BethesdaStudios/status/1772655959740985761

**Comment by gir489returns** [comment] 2024-03-26 23:57
> https://twitter.com/BethesdaStudios/status/1772655959740985761

Thanks! I wish they had also fixed #913 but I guess asking Bethesda to do their job is a bridge too far, especially since they broke it with the patch.

**Comment by Deebz96** [comment] 2024-03-26 23:59
Actually I see now that you were referring to an issue other than this one we're talking on. Today's hotfix addressed the "Oh no, what will we do" bug. The guard dialogue bug is different. It's actually caused by Spriggit merges of the community patch. Download this version to fix it: https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/releases/download/0.1.1/StarfieldCommunityPatch.0.1.1.10Mar24.No.Spriggit.zip

**Comment by gir489returns** [comment] 2024-03-26 23:59
> Actually I see now that you were referring to an issue other than this one we're talking on. Today's hotfix addressed the "Oh no, what will we do" bug. The guard dialogue bug is different. It's actually caused by Spriggit merges of the community patch. Download this version to fix it: https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/releases/download/0.1.1/StarfieldCommunityPatch.0.1.1.10Mar24.No.Spriggit.zip

Thanks!

**Closed** 2024-03-31 18:57 UTC
Labels: Platform: Xbox, Type: Missions & Dialogue
