### ISSUE TITLE
PG's head turns left while running

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#59] opened 2023-09-05 20:31 UTC
A lot of times while running, my character's head turns all the way to the left and it only fixes itself if I turn the camera around and look back 

---

## Details 
Nothing, it happens everywhere, everytime randomly 

## Game Version
1.7.23

## New Game
Yes

## Reproduction Steps
Nothing, just run and it will likely happen in 30 seconds or less

**Comment by n0tPuffer** [comment] 2023-09-10 08:05
For me, it seems to happen after I press jump or fall down in third-person view while also scanning at the same time.

**Comment by Constellation-VASCO** [comment] 2023-09-10 15:30
I'm able to consistently reproduce this by sprinting forwards, jumping and landing. You can also temporarily fix it by going into first person.

**Comment by Constellation-VASCO** [comment] 2023-09-11 20:46
Seems to be specifically an animation bug with the hard landing reaction while sprinting with no weapons equipped of walk style 1. If you jump while sprinting, but don't jump high enough, or soften your landing with the boost pack enough to not trigger the hard landing reaction animation the bug does not occur. landing without continuing to sprint, or landing while sprinting with a weapon out, will not cause this bug to occur.

**Comment by Constellation-VASCO** [comment] 2023-09-11 20:57
Can confirm exactly what TrinDiesel states above. Obviously, this bug is specific to third person view.

**Comment by Pickysaurus** [comment] 2023-10-23 15:23
Duplicate of https://www.starfieldpatch.dev/issues/247 #247

**Closed by Pickysaurus** 2023-10-23 15:23 UTC
Labels: Platform: PC (Steam), Type: Animations
