### ISSUE TITLE
Unable to talk to Brogan

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#9] opened 2023-09-01 03:47 UTC
- Kreet research lab, in meet brogan
- Went outside but no dialog initiated with brogan
- I can freely move, while the 3 pirates just stand there
- When I interact with them they say generic lines, but no dialog

---

## Game Version
1.7.23

## New Game
No

## Reproduction Steps
Happened on my first playthrough.

**Comment by RPINerd** [comment] 2023-09-01 18:29
Unable to reproduce, I was sneaking at the time and the stealth meter filled up green until I reached the top of the stairs where dialogue activated

**Comment by dragonjet** [comment] 2023-09-02 00:38
save file that should be able to replicate it

[starfield_save_brogan_no_talk.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/12502115/starfield_save_brogan_no_talk.zip)

**Comment by Constellation-VASCO** [comment] 2023-09-02 11:30
connect

**Comment by Aurelianis** [comment] 2024-05-18 20:27
While the save attached does replicate the issue and I've seen reports from when the game was first released about this issue, I have not been able to replicate it in a new save replaying from the start at least 20x. So closing this as unable to reproduce. If the issue occurs again in v1.11.36.0 (current Starfield version as of this post) or later feel free to let us know and we can investigate more.

**Closed** 2024-05-18 20:42 UTC
Labels: Platform: PC (Steam), Type: Missions & Dialogue
