### ISSUE TITLE
Empty ships & Cargo bays won't open

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#496] opened 2023-10-31 09:51 UTC
Ships are empty when I board them. Ships' cargo bay won't open when found on planets either.

---

## Details 
Ships, when space fighting, or even on missions, now are empty when boarding them. As long as the ship is not part of a mission, I can still take ownership of it. However, if this is not so, for example, if it is part of a Board Mission, I must destroy the ship to get the rewards, but, obviously, not the ship. 

Also, ships that have landed on a planet, no longer open their cargo bays. Their crew won't be found in the ship's proximity either. 

## Game Version
1.7.33

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
1. Follow normal mechanics when fighting a spaceship. 
2. Board the ship to find it empty. 
3. Taking over the ship still grants ownership, but doesn't mark Board Missions as complete. 
SECOND ISSUE
1. Land on a planet, moon, and wait for a ship to appear.
2. Approach the ship
3. The ship's cargo bay is closed, crew is nowhere to be found, and therefore, there is no access to the ship.

**Comment by kayahr** [comment] 2023-11-16 07:51
May be a duplicate of issue #268

**Comment by Aurelianis** [comment] 2024-05-19 16:23
Closing as a duplicate of https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/221

**Closed by Aurelianis** 2024-05-19 16:23 UTC
Labels: Platform: Xbox, Type: Ships
