### ISSUE TITLE
Barret's debrief after Neon/Ryujin mission ends

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#388] opened 2023-10-25 07:34 UTC
Your dialogue choice: "I don't just corporations, Simple." should probably be "I don't trust corporations, Simple."

---

## Details 
Unsure of Quest ID, May be end of Ryujin or MQ side notes, or Barrets

## Game Version
1.733.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Its a simple dialogue "Ooopsie" as Barret might say.

**Comment by Pickysaurus** [comment] 2023-10-27 16:17
Duplicate of #383

**Closed by Pickysaurus** 2023-10-27 16:17 UTC
Labels: duplicate, Platform: PC (Steam), Type: Missions & Dialogue
