### ISSUE TITLE
Vasco Robot First Pirate scene

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#5] opened 2023-09-01 01:16 UTC
Vasco audio issue.

---

## Details 
Vasco the robot helps in the fight against the pirates. Once the fight is over you can still hear his gun shooting.

## Game Version
1

## New Game
Yes

## Reproduction Steps
Just play the game.

**Comment by RPINerd** [comment] 2023-09-01 18:07
Cannot duplicate this, his audio never got hung for me during the entire pirate outpost

**Comment by Constellation-VASCO** [comment] 2023-09-02 11:41
Comment

**Comment by Aurelianis** [comment] 2024-05-18 20:05
Played this scene multiple times (probably at least 20, if not more) and have never had this issue happen. Closing due to not being able to reproduce.

**Closed by Aurelianis** 2024-05-18 20:05 UTC
Labels: Platform: PC (Steam), Type: Audio, qa-needs-reproducing
