### ISSUE TITLE
Typo 15

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#459] opened 2023-10-29 03:15 UTC
35B249 - nonsensical player line.

---

## Details 
text reads: I don't just corporations. Simple.
should (probably) read: I don't trust corporations. Simple.

just based on the context of the conversation, the response given, and the other options you can choose.

## Game Version
1.7.36

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
check the record, play the ryujin quest. this is from a conversation with barrett after finishing Executive Level, i believe.

**Comment by Pickysaurus** [comment] 2023-11-01 20:16
Duplicate of #383

**Closed by Pickysaurus** 2023-11-01 20:16 UTC
Labels: Platform: PC (Steam), Type: Missions & Dialogue, Fix Ready
