### ISSUE TITLE
Unity No Helmet

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#952] opened 2024-05-11 05:32 UTC
When talking to self at Unity, She isn't carrying a helmet. 1st game and again in NG+.

---

## Details 
n/a

## Game Version
1.10.32.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
just played the game right through.

**Comment by Aurelianis** [comment] 2024-05-19 20:42
Confirmed. Happens every time.

The odd thing is that if you use setstage 0024EF9C 1 to skip straight to the Unity, the helmet is there. Something to look at when working on a fix for this.

**Comment by Deebz96** [comment] 2024-05-25 17:08
This one happened to me in a variant universe, but not any of the normal ones. Seems to be a new issue. Interestingly, the dead members of Constellation no longer appear in the unity anymore either.

**Comment by Aurelianis** [comment] 2024-05-25 19:32
SFCP fixes Constellation showing up in the Unity when they shouldn’t in variant universes.

**Closed** 2024-08-13 21:51 UTC
Labels: duplicate, Platform: PC (Steam), Type: Items
