### ISSUE TITLE
Noticable stutter when pulling out rarer items

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#112] opened 2023-09-09 17:15 UTC
There's an issue that's been observed when you pull out weapons of higher rarity. Originally, I've observed when you have Heller's Cutter and a white rarity gun, pulling out your scanner causes a stutter/hiccup every time you pull it out regardless of where you are. My best guess is that it's related to what happens when the weapon swaps (as it does with the scanner) and something to do with varying rarity weapons.

---

## Details 
This happens (as far as I can tell) regardless of weapons.

## Game Version
v1.7.23.0

## New Game
Yes

## Reproduction Steps
Noticed this happens under the following scenarios:

- Have the regular cutter and a legendary gun and walk and open the scanner. There'll be a noticeable hiccup (with potentially varying lengths in time spent hiccupping) while the scanner is being opened.
- Have Heller's Cutter and a white rarity gun. Then walk and open the scanner. You'll notice the same hiccup while the scanner is being opened. Probably due to Heller's Cutter not being white rarity.

**Comment by Constellation-VASCO** [comment] 2023-09-10 22:50
This happens only when cycling between weapons with perks (legendary, epic for example)

Never happens when switching between 2 common items that are assigned to the favorite hotkeys, but switching from or to a legendary weapon (example) that is assigned to the favorites will result in a stutter which i have been able to reproduce in 100% of the cases.

Another problem is switching to a scanner while having such item equipped also causes a halt. Pretty major issue that has forced me to only use common weapons.

**Comment by SanichSanSPb** [comment] 2023-09-11 09:30
A few clarifications on the issue.
1) the problem arises with weapons.
2) the problem is only with weapons that have mods that change the damage.

using the example of a weapon with 1 mod:
If there is an Extended Magazine mod for the weapon then there will be no problems.
If the weapon has a Shattering mod, then there will be a problem. even with 1 mod.

If a weapon has 3 damage-increasing mods and you switch to a white weapon (for example, turn on the scanner to which a white cutter is attached), then the problem increases 3 times. if you switch between two weapons, each of which has 3 mods that increase damage, then the freeze time will increase by 6 (!!!) times.

The root of the problem is that weapons, for some reason, are considered an element of equipment in the game, like a spacesuit. that is, its bonuses apply to ALL inventory (and possibly to all items in the warehouse and cargo compartment). Each time a weapon is swapped, these stat changes are first undone from the removed weapon and then applied from the picked weapon to all weapons in the inventory (and possibly all items in the storage area and cargo bay).

To see this you need to open your inventory and change the weapon in your inventory. at the same time, you will see how the damage indicators of all weapons in the inventory change (clearly visible on weapons with the Shattering property) - first they are reset to the basic ones (indicators of weapons without mods with upgrades made on the workbench) then the mods of the weapon you took are applied to all weapons in the inventory in your hands.

Weapon modifications made at the workbench do not cause such problems, only the properties of the weapon.

**Comment by Constellation-VASCO** [comment] 2023-10-27 16:32
This issue was fixed by Bethesda with the Sept 25th patch. Changelog notice:
"Hand Scanner: Addressed an issue where the Hand Scanner caused hitching."

**Comment by Pickysaurus** [comment] 2023-11-09 19:03
Seems to have been fixed by a game update.

**Closed by Pickysaurus** 2023-11-09 19:03 UTC
Labels: Platform: PC (Steam), Type: Items
