### ISSUE TITLE
NG+ "You" companion appearance bug

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#779] opened 2023-12-26 10:29 UTC
"You" companion doesn't just copy your appearance, this NPC is permanently connected to your character and you can't change your appearance without changing theirs.

---

## Details 
When you are in a certain universe and have "you" joined your crew, when you change your face, hair, whatever in "Enhance" - no matter if other "you" is following or somewhere far away, their appearance will also change accordingly.

## Game Version
1.8.88.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Enter the universe 1801B9, persuade another "You" to join, then you can assign them to a post or have them as a follower - it doesn't matter.
Go to "Enhance" and make any change".
When you see another "You" next time - their appearance will exactly match your CHANGED appearance.

**Comment by Aurelianis** [comment] 2024-05-19 20:53
This is a duplicate of https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/522

**Closed by Aurelianis** 2024-05-19 20:53 UTC
Labels: Platform: PC (Steam), Type: NPCs
