### ISSUE TITLE
Trackers Alliance HQ affected by load order

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1038] opened 2024-06-21 22:00 UTC
Found that Trackers Alliance HQ is affected by load order of Starfield Community Patch v0.1.6.  If starfieldcommunitypatch.esm is loaded after sfbgs023.esm & sfta01.esm, then the Trackers Alliance HQ is missing floors, other structure, lights, and most items; NPCs are there but completely dark.

---

## Details 
New to v0.1.6 of SFCP; did not occur with v0.1.5.  Also, does not occur when, in Plugins.txt, *starfieldcommunitypatch.esm is placed before all official Bethesda *sfbgs023.esm and *sfta01.esm.

## Game Version
1.12.32.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
In Plugins.txt, place *starfieldcommunitypatch.esm (version 0.1.6) after *sfbgs023.esm and *sfta01.esm, as seems to be recommended.  Walk in to Trackers Alliance HQ in Akila.  See all structure (including floors and lights) missing.

**Comment by Deebz96** [comment] 2024-06-21 22:07
Unable to replicate. Load order should not cause this issue regardless, as the SFCP does not yet touch the TA content.

Many people seem to be experiencing issues such as this at random since the June update. Some say it may be caused by the game loading small and medium masters in an unusual way. Others say it may be caused by using .esp plugins, as those are not loaded correctly by the game. It may also be caused by running too many mods, as some people report issues like this occurring when using around 120+ plugins.

Regardless, this mod is not directly responsible. Something deeper is going on with mod support as a whole, which isn't fully understood just yet. Will need to be addressed by Bethesda on the engine level.

**Closed by Deebz96** 2024-06-21 22:07 UTC
Labels: invalid, Platform: PC (Steam), Type: Locations

**Comment by Constellation-VASCO** [comment] 2024-06-21 22:33
Strange.  I tried with all other plugins disabled, and still had the issue.  Only when either placing starfieldcommunitypatch.esm earlier in load order or disabling it, did it the Trackers HQ work properly.  Guess I'll keep my load order the same until other issues pop up.  Thanks for looking into it.
