### ISSUE TITLE
Fast Travel Unavailable during Starborn

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#80] opened 2023-09-07 17:04 UTC
After escaping from the Starborn at the beginning of the mission Starborn, trying to fast travel anywhere will give a message the fast travel is unavailable at this time. Every method of landing on a planet or moving to another system is impossible, except for selecting a mission, looking towards the waypoint, and holding R to move to that system. Landing will still be impossible.

---

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
Directly after the final step of All That Money Can Buy that says to take off from Neon, you will be put into the mission Starborn. A ship will appear and force dialogue, and upon the final option to either flee, fight, or jettison the artifact, select flee. Fast travel will be unavailable so you need to flee by looking towards the waypoint. Trying to land at Jemison or traveling to another system or city through the map will not work. I'm unsure if fighting or jettisoning will give a different result, but might be worth a try.

**Comment by TESWartortle** [comment] 2023-12-17 19:14
Can't replicate on 1.8.88

**Comment by Aurelianis** [comment] 2024-05-19 04:01
This seems to have been fixed by Bethesda. Closing as unable to reproduce. If it does occur again please let us know.

**Closed by Aurelianis** 2024-05-19 04:01 UTC
Labels: Platform: PC (Steam), Type: Ships
