### ISSUE TITLE
ECS Constant cannot be found

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#509] opened 2023-11-01 15:15 UTC
After enabling the crew of the ECS Constant with a new grav drive in the mission "First Contact", the subsequent activity "Locate the ECS Constant" is added.  A marker is provided but the ship is not there.

---

## Details 
I am given a new activity mission to "Locate the ECS Contact" when completing the "First Contact" mission via the Grav Drive ending.  At this point I am given a new activity titled "Locate ECS Constant" - This typically places a marker in the Porima system where it's first found but the ship is not there.  Sometimes the marker is in another system or planet but every time I grav drive to the location the game provides the ship is nowhere to be found.

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
I have never finished this mission so it was never difficult to recreate.  I am unaware if my situation is unique but I cannot locate a solution to this issue, even if it's user error (which is also possible lol)

**Comment by Pickysaurus** [comment] 2023-11-02 08:34
Duplicate of #243

**Closed by Pickysaurus** 2023-11-02 08:34 UTC
Labels: Platform: PC (Steam), Type: Missions & Dialogue
