### ISSUE TITLE
Blast Zone Rocks missing

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#534] opened 2023-11-03 12:38 UTC
In the Akila City mission Blast zone, the rocks you are supposed to blast/cut away with your cutter are missing making it impossible to complete the mission

---

## Details 
The rocks that you are supposed to blast away with your cutter are missing from the area they are marked at with the mission markers

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Accept the mission in Akilia City

**Comment by Pickysaurus** [comment] 2023-11-09 18:51
DUPLICATE OF #325

**Closed by Pickysaurus** 2023-11-09 18:51 UTC
Labels: Platform: PC (Steam), Type: Missions & Dialogue
