### ISSUE TITLE
'All that Money can Buy' Glitch

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#120] opened 2023-09-10 05:51 UTC
Towards the very end of the mission after you deal with Slayton you need to go to your ship so you can bring the artifact back to the lodge on new atlantis. Once you get to the ship, however, you are unable to launch into space without speaking with Walter Stroud. Once you speak with him, the conversation will not end and you are stuck zoomed in and looking at Walter forever. The only way I have been able to progress through this is by using console commands to kill, then resurrect Walter. 

---

## Details 
I believe the quest ID is 002C1C9B. Not sure of the stage number. 

## Game Version
1.7.23

## New Game
No

## Reproduction Steps
I am not sure, but there seem to be others with the same issue:

https://www.reddit.com/r/Starfield/comments/168ss2x/cant_progress_main_questline_all_that_money_can/

**Comment by Aurelianis** [comment] 2024-05-19 03:57
Closing as duplicate of https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/79

**Closed by Aurelianis** 2024-05-19 03:57 UTC
Labels: duplicate, Platform: PC (Steam), Type: Missions & Dialogue
