### ISSUE TITLE
Ng+ Universe roll seed bug 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#106] opened 2023-09-09 10:10 UTC
Platform: PC (Steam)

Time/date of bug encountered: September 6th 2023

When starting new game plus, in certain circumstances you'll never be able to save or open your inventory.

---

## Details 
You have a chance to get a universe seed where the lodge gets alternative versions where andreja for example could show up with cultist and kill you, and in this universe you'll never be able to save your game or access your inventory. I'm noticing this happening with each unique new game universe unless it's a vanilla new game plus seeds with no changes to faction NPCs or the lodge

Steps ive done to troubleshoot : validated steam files, full clean install ( made sure to delete app data stuff too ) and even started a new game to try to see if my game was just being silly, but the issue persist. Its preventing me from experiencing new game plus content that id otherwise would be able to experience if this bug was interfering with saving.

Solution for now : 

There are specific console commands that allow you to start these secret seeds , however it's not ideal as it ruins the the surprise elements of discovering these. Solution found here : https://reddit.com/r/Starfield/s/Xhuht9OiDN

## Game Version
v1.7.23.0

## New Game
Yes

## Reproduction Steps
Start a new game, either new game plus or regular new game, finish the main storyline, go to the unity and make a hard save. Then keep entering the unity, get reborn, and then when your in your ship in the beginning of new game plus, check to see if your inventory is not available to open and you get a popup for this, and then check to see if you can't quicksave or save. If confirmed, go to the lodge and let the special scene play out.

These are fully fleshed out, an example being if the hunter kills everyone , you can go to the Eye and you get specific dialogue to use it. It seems this wasn't intentional as the hunter even says " I'm sure this isn't the first time you've seen the lodge like this "

**Comment by juliocoliveira** [comment] 2023-09-11 17:26
I think this is not a bug, but an intentional game feature.

**Comment by spkyghzt** [comment] 2023-09-12 05:52
The only thing the ruins things is not being able to save or open your inventory that makes me believe it's a bug.

**Comment by Constellation-VASCO** [comment] 2023-09-14 02:43
@juliocoliveira what is your source for this being an intentional game feature? This appears to be a bug as some users are able to load the same NG+ variant and not experience this issue. For example I experienced the issue on the lodge "sarah is a plant" variant and was unable to save or load inventory. However, other users have reported getting this seed variation and being able to save and use player inventory. Some users have also been able to recover from this by opening ship inventory and switching to player or opening console and click the OK dialogue to the warning. 

There are also variations that require the user to loot and read a special item, which is blocked by being unable to access inventory.

Do you have a source with Bethesda that has confirmed this is a feature and not a bug?

**Comment by juliocoliveira** [comment] 2023-09-14 03:44
Zero source, as I said "I THINK", never said that was an absolute truth right from Bethesda developers.
But some people think that is intentional, a random layer of difficulty, an universe that you cannot save or use your inventory,

**Comment by spkyghzt** [comment] 2023-09-18 10:15
It's likely a bug with the quest stages or a variable ( like how certain cutscenes and other variables don't allow you to save or access your inventory in certain moments in the game that I won't spoil ) which could easily be fixed in CK when it releases or by Bethesda. This is fixable currently only with use of console commands.

**Comment by Aurelianis** [comment] 2024-05-19 02:45
This was fixed in v1.8.86 
"Fixed an issue that could temporarily prevent opening the inventory or saving after entering the Unity."

**Closed by Aurelianis** 2024-05-19 02:45 UTC
Labels: Platform: PC (Steam), Type: Missions & Dialogue
