### ISSUE TITLE
Post High Price to Pay elevator bug

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1136] opened 2024-09-02 01:53 UTC
The Well elevator leading to NAT Station Elevator is no longer interactable after the High Price to Pay quest

---

## Game Version
1.13.61

## Language
Spanish (ES)

## New Game
No

## Reproduction Steps
Play the High Price to Pay quest. This quest blocks the elevator because it sends you to the opposite elevator which leaves for the spaceport to complete it. Afterwards the elevator never works again.

**Comment by Deebz96** [comment] 2024-09-02 02:04
Dupe of #839

**Closed by Deebz96** 2024-09-02 02:04 UTC
Labels: duplicate, Platform: PC (Steam), Type: Missions & Dialogue
