### ISSUE TITLE
All that Money can buy 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#272] opened 2023-09-27 03:21 UTC
I’m playing “All that Money can buy” post patch 9/26/23 and I am locked in dialogue with Walter Stroud. I have recreated this issue many times by doing the whole mission and entering my ship (boarding) and entering by going directly through the cockpit. When (boarding) I spawn into the ship after it had supposedly been released and engage in conversation with stroud. I run through all dialog options and the mission completes rewarding me with items and then I can’t exit the convo. I am just stuck staring at stroud until I reload a previous save. If I enter through the cockpit, stroud engages with me before I can control the ship, I run through all dialog options, complete the mission, am rewarded with quest items and I am frozen not able to “take off” “get up” or “get out”

---

## Details 
N/A

## Game Version
1.7.33.0

## New Game
No

## Reproduction Steps
1. Start mission with stroud 
2. Complete mission “All that money can buy”
3. Start talk to stroud on ship
4. Stuck staring at stroud forever

**Comment by Constellation-VASCO** [comment] 2023-10-14 11:33
Walter Stroud in general is just broken. If you manage to get past this with console commands, he is stuck with you forever and will get locked the same way in final convos for his other quests. Please fix this. Has been the biggest glitch for me.

**Comment by Aurelianis** [comment] 2024-05-19 03:54
Closing as Duplicate of https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/120

**Closed** 2024-05-19 03:58 UTC
Labels: duplicate, Platform: Xbox, Type: Missions & Dialogue
