### ISSUE TITLE
Cooking station Glitch

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#300] opened 2023-10-03 08:36 UTC
The items produced on the Stroud-Eklund Mess Hall 3x2 cooking station do not go to the player's inventory when operated. Regardless of the batch size, only one item is produced and said item appears on the opposite side of the wall behind the cooking station.

---

## Game Version
1.7.33.0

## New Game
Yes

## Reproduction Steps
Go to the cooking station

Produce any item

Inspect the opposite side of the wall behind the cooking station

**Comment by DigitalHype** [comment] 2023-10-03 17:33
Regarding "Needs vetting" status. I can confirm experiencing the exact same behavior as described.

**Comment by Pickysaurus** [comment] 2023-11-15 14:12
Duplicate of #526

**Closed by Pickysaurus** 2023-11-15 14:12 UTC
Labels: Platform: PC (Steam), Type: Ships
