### ISSUE TITLE
New Atlantis Ship Services Technician Problem

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#111] opened 2023-09-09 15:16 UTC
The Technician is not restocking his credits after going reaching 0 credits and me waiting a few hundred universal hours.

---

## Game Version
1.7.23.8

## New Game
Yes

## Reproduction Steps
Get the Technician down to 0 credits, then wait.

**Comment by Deebz96** [comment] 2024-08-23 19:19
Unable to reproduce over multiple playthroughs. Marking as invalid, unless more specific reproduction steps can be provided.

**Closed by Deebz96** 2024-08-23 19:19 UTC
Labels: invalid, Platform: Xbox, Type: NPCs
