### ISSUE TITLE
Rejuvenation perk not working

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#331] opened 2023-10-09 19:42 UTC
In combat portion of Rejuvenation does not work. No health regeneration while in combat.

---

## Details 
According to one user on Nexus mods, this has to do with the actor value HealRate being set to 0 in combat regardless of perks.

## Game Version
1.7.36

## New Game
Yes

## Reproduction Steps
Take rank3 or 4 of rejuvenation and take damage in combat. Will never regen health.

**Comment by Pickysaurus** [comment] 2023-10-21 13:57
Duplicate of #141 <https://www.starfieldpatch.dev/issues/141>

**Closed by Pickysaurus** 2023-10-21 13:57 UTC
Labels: duplicate, Platform: PC (Steam), Type: Perks & Skills
