### ISSUE TITLE
Crash: Outposts Build Menu

### ISSUE THREAD

**Issue by VoidFletcher** [Starfield-Community-Patch/Starfield-Community-Patch#33] opened 2023-09-03 14:16 UTC
### Details
When opening the build menu or the scanner at an outpost that has become bugged, the game will immediately hang every time. I've not managed to identify what causes an outpost to enter this state or any workarounds. Fast traveling to another location makes the outpost landing pad marker disappear.

Information that may or may not help:

- This happened after building my third outpost and returning to my first outpost.
- I've recently received an achievement stating that I've harvested 500 resources from outposts.
- My first outpost has 4 extractors and a large landing pad.
- Two crew members are assigned to the outpost, but unassigning them does not affect the crash.
- Several people on Reddit and Steam are reporting the same issue.
- PC Platform, Steam. Also reported on Xbox

Let me know if there are any other details I can provide.

### Game Version
1.7.23.0

### New Game
Unknown

### Reproduction Steps
Unfortunately, I do not have reproduction steps in order to get the outpost bugged.

**Comment by Constellation-VASCO** [comment] 2023-10-11 12:25
I can corroborate this one, and unfortunately don't know the steps to reproduce it. I've posted about it on Reddit, and indeed other people have encountered the same problem.
My post:
1.https://www.reddit.com/r/Starfield/comments/175a079/crash_when_opening_scanner_in_outposts/
Their posts:
1. https://www.reddit.com/r/Starfield/comments/16g0ljb/crashing_in_outpost_build_mode/
2. https://www.reddit.com/r/Starfield/comments/167nahr/starfield_crashing_when_accessing_outpost/
3. https://www.reddit.com/r/Starfield/comments/16urj8l/game_breaking_bug_repeat_crash_to_desktop_when/
4. https://www.reddit.com/r/Starfield/comments/16j07mt/scanner_crashing_game_at_outpost/

**Comment by Deebz96** [comment] 2024-08-23 18:58
Closing this one as dated. I have not had this issue since launch. Will need more specific reproduction steps.

**Closed by Deebz96** 2024-08-23 18:58 UTC
Labels: Platform: PC (Steam), Platform: PC (Xbox), Type: Outposts
