### ISSUE TITLE
Ship Piracy Empty Ships without any Crew

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#241] opened 2023-09-19 06:47 UTC
Disable and board a hostile ship (Ecliptic, Varuun, Spacer, or Crimson Fleet) and there will be no crew aboard even though the ship (when you undock will still shoot at you).

---

## Details 
Happens after you fly an unregistered ship to Wolf Station (in order to sell contraband that was onboard) rather than to a city to register it. After this all ships you board will be empty.

## Game Version
1.7.29.0

## New Game
Yes

## Reproduction Steps
As above.

**Comment by Constellation-VASCO** [comment] 2023-10-27 14:45
Can confirm this issue. Mod to fix and discussion on the topic here:

https://www.nexusmods.com/starfield/mods/5668

**Comment by kayahr** [comment] 2023-11-16 07:50
May be a duplicate of issue #268

**Comment by Aurelianis** [comment] 2024-05-19 16:23
Closing as a duplicate of https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/221

**Closed by Aurelianis** 2024-05-19 16:23 UTC
Labels: Platform: PC (Steam), Type: Ships
