### ISSUE TITLE
Madame Sauvage's Place upstairs door lock

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#148] opened 2023-09-11 11:10 UTC
During the quest 'The Audition' on Neon, the door in Madame Suavage's Place to the upstairs area where the quest takes place can become locked again if you quit your conversation with the npcs there and leave Madame Sauvage's Place.

---

## Game Version
Full Release Version

## New Game
No

## Reproduction Steps
Go to Madame Sauvage's Place, talk to the Striker npc downstairs about joining the gang, follow her upstairs as the door unlocks and she takes you to her friends.
Talk to Briggs about joining the gang but then exit the conversation instead of accepting, leave Madame Sauvage's Place, go do other quests, travel to other planets, then return later and go to Madame Sauvage's Place and find that the door to upstairs is locked/inaccessible with no way to open it besides a console command.

**Comment by Bobbyclue** [comment] 2023-09-26 18:02
Possibly needs the "No Respawn" flag

**Comment by Aurelianis** [comment] 2024-05-19 04:12
Duplicate of https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/48
Fixed in v1.10.31.0
"The Audition: Addressed an issue with later passing a door if the area was left while Andrea escorted the player."

**Closed by Aurelianis** 2024-05-19 04:12 UTC
Labels: Platform: PC (Steam), Type: Locations
