### ISSUE TITLE
Ship interaction inventory AND cargo (Dr Banglawala)

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#56] opened 2023-09-05 11:56 UTC
I got a ship interaction where a scientist offered to pay me for any resources I mighty have that they need. I was forced to decline because none of the resources were in my inventory but in my ship's cargo instead, and seeing how you cannot stand up to access the ship's cargo while in orbit and cannot access inventories in dialogue, ship and player inventories should both be used.

---

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
It's a random encounter

**Comment by TESWartortle** [comment] 2023-12-17 02:19
Same issue as #271. Fixed by this mod and able to be integrated to SFCP https://www.nexusmods.com/starfield/mods/7654

**Comment by Aurelianis** [comment] 2024-05-19 15:54
SE_Player_AC03 "Research Outpost" [QUST:00063CF7]

This seems to have been fixed. Looking at the script attached to the quest: Fragments:Scenes:SF_Player_HailTemplate_SE_Pl_00063A85

It checks the Player Inventory and Cargo:

Function Fragment_Phase_04_Begin()
  spaceshipreference PlayerShip = Alias_PlayerShip.GetShipRef()
  ObjectReference PlayerRef = Game.GetPlayer() as ObjectReference
  Int CargoShipParts01 = PlayerShip.GetItemCount(InorgRareLithium as Form)
  Int PlayerShipParts01 = PlayerRef.GetItemCount(InorgRareLithium as Form)
  Int TotalParts01 = CargoShipParts01 + PlayerShipParts01
  SE_Player_AC03_Inventory01.SetValue(TotalParts01 as Float)
  Int CargoShipParts02 = PlayerShip.GetItemCount(InorgRarePlatinum as Form)
  Int PlayerShipParts02 = PlayerRef.GetItemCount(InorgRarePlatinum as Form)
  Int TotalParts02 = CargoShipParts02 + PlayerShipParts02
  SE_Player_AC03_Inventory02.SetValue(TotalParts02 as Float)
  Int CargoShipParts03 = PlayerShip.GetItemCount(InorgRareVanadium as Form)
  Int PlayerShipParts03 = PlayerRef.GetItemCount(InorgRareVanadium as Form)
  Int TotalParts03 = CargoShipParts02 + PlayerShipParts03
  SE_Player_AC03_Inventory03.SetValue(TotalParts03 as Float)
EndFunction

Just noting for now. Will test in game to verify that the script is working as intended.

**Comment by Aurelianis** [comment] 2024-05-23 17:41
Verified that this is no longer an issue as of v1.11.36.0. Ran into Dr. Sohla Banglawala today when playing the game. Removed all Lithium, Platinum, and Vanadium from my inventory and added them to my ship's cargo. Dialogue picked up that I had all 3 available to give to her.

**Closed by Aurelianis** 2024-05-23 17:41 UTC
Labels: Platform: PC (Steam), Type: Ships
