### ISSUE TITLE
Crates - Crate Of Exotic Liquors, Etc - No bounds

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#906] opened 2024-03-12 16:13 UTC
Crates - Crate Of Exotic Liquors, Etc - No bounds

---

## Details 
No bounds set for Crate of Liquors Misc 002182C5 and a few of the other crates in that sequence. I copied over bounds from Crate of Hygene Products 002182CA which is the same NIF. Crate of Liquors is found placed in the wild, namely Siren Of The Stars, otherwise it really wouldn't matter much because they are mostly quest items.

## Game Version
1.9.71.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Description

**Comment by Deebz96** [comment] 2024-09-29 23:15
This is true, but I'm unable to see an issue caused by this in the game. Surprisingly, it seems like NPC navmesh even correctly adapts to this prop being in their way, which is one of the only issues I know of that is caused by this type of issue.

I'll mark this as wontfix since this seems to be a non-issue. Though if there is an issue which can be explained, I'm open to re-checking this.

**Closed by Deebz96** 2024-09-29 23:15 UTC
Labels: wontfix, Platform: PC (Steam), Type: Items
