### ISSUE TITLE
Generic recovery mission by Denis Averin malfunc.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#929] opened 2024-04-07 14:27 UTC
the generic recovery missions given by Denis Averin, Cydonia UC Exchange, no longer generates all needed items to recover on mission locations.

i played these missions along time ago in september, returning now. i updated SFSE and SCP so far, as well as the official game. back in september the mission was to recover 5 generic weapons of a random POI. in the POI's main chest were allways 5 mission required weapons present.
now its only 1 weapon. picking it up marks mission complete to return to Denis Averin. back at Denis Averin the turn in dialog returns a dialog from Denis, the starfare need to retrieve all neded 5 weapons.
i made the generic missions 5x in total, all yield only 1 mission weapon each. ( i liked this mission for its simplicity )

---

## Details 
Generic recovery mission
Denis Averin, UC Exchange, Cydonia
only 1 mission item is generated, instead of all needed 5. 5 were allways generated in sep/2023

## Game Version
1.8.86.0

## Language
German (DE)

## New Game
Yes

## Reproduction Steps
doing generic recovery mission given by Denis Averin

**Comment by Aurelianis** [comment] 2024-04-07 19:26
Duplicate of #921

**Comment by Constellation-VASCO** [comment] 2024-04-12 22:06
> Duplicate of #921
i was like browsing here before, on 921 my brain was like afk then

**Comment by Aurelianis** [comment] 2024-05-19 04:33
Closing as duplicate

**Closed by Aurelianis** 2024-05-19 04:33 UTC
Labels: duplicate, Platform: PC (Steam), Type: Missions & Dialogue
