### ISSUE TITLE
Freighter exit places player underneath ship

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#105] opened 2023-09-09 10:02 UTC
When exiting the freighter at the Freighter Site involved in the quest "Freight Fright" from Denis in Cydonia, the player is placed beneath the freighter's landing gear instead of outside the door.

---

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
- Accept quest from Denis in Cydonia
- Go to Freighter Site PoI on Mars
- Enter freighter
- Leave freighter via the door

**Comment by Constellation-VASCO** [comment] 2024-01-20 12:26
I provided a fix...

https://www.nexusmods.com/starfield/mods/8181

**Comment by Aurelianis** [comment] 2024-05-19 15:35
Closing as a duplicate of https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/13

**Closed by Aurelianis** 2024-05-19 15:35 UTC
Labels: Platform: PC (Steam), Type: Locations
