### ISSUE TITLE
sarah causing dialogue softlocks

### ISSUE THREAD

**Issue by khirasier** [Starfield-Community-Patch/Starfield-Community-Patch#125] opened 2023-09-10 12:52 UTC
if you have sarah on your ship crew or outpost she can sometimes start dialogue she is meant to do inside the lodge and cause the other people she is supposed to talk to in the conversation arent there you will just get stuck in place in dialogue unable to exit unless you reload a save. seems to specifically happen with dialogues between her and walter.

**Comment by juliocoliveira** [comment] 2023-09-11 17:44
I created an issue about this, I didn't saw this one.
Here is my issue text:
Sarah triggers a forced dialog with no option to exit, after clicking on any dialog option, it shows only her face and no text.
She keeps talking to you randomly.
I found out if you take her to the lodge where is Walter there, she are able to continue the dialog, and this fixes the issue.
She keep talking that Walter is paying for the funeral and repairs, and if Walter is not there, the dialog freezes and you cannot do anything.
It does not seem to be attached to any quest, At least I don't remember.
The issue is that she triggers the dialog if you are on the lodge or not, if Walter is there or not, and that get you stuck with not option to exit.

**Comment by khirasier** [comment] 2023-09-12 14:11
that was one of the dialogs that caused the softlock for me but there was also another one that happened earlier in the game too though i cant remember what that dialogue was about, though that one wasnt a forced conversation, i just talked to her and she initiated a dialogue that should be played inside the lodge

**Comment by Deebz96** [comment] 2024-08-23 19:29
This was fixed by Bethesda.

**Closed by Deebz96** 2024-08-23 19:29 UTC
