### ISSUE TITLE
Crash on Akila in Matters of the Hart quest

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#651] opened 2023-11-19 22:46 UTC
Every time I try to take Sam to the statue in Akila to turn in one of the last steps in the Matters of the Hart quest, the game crashes. I think it's something in my save file as I've even tried loading it on Xbox and Cloud and it crashes there in all of them. So I thought it might be something you might be able to patch a fix since it's reading something in my save I guess.

---

## Details 
See above

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Unknown

**Comment by Aurelianis** [comment] 2024-05-19 03:45
Unable to reproduce having done this quest over a dozen times. Likely save game corruption. Closing this is unable to reproduce but if you do run into this issue again let us know. A save file might help as well.

**Closed by Aurelianis** 2024-05-19 03:45 UTC
Labels: Platform: PC (Xbox), Type: Missions & Dialogue
